# Generated by Django 3.1.13 on 2021-08-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20210824_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='author',
            new_name='pokemon',
        ),
    ]
