# Generated by Django 3.1.13 on 2021-09-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20210913_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Имя покемона на русском'),
        ),
    ]
